### ISSUE TITLE
There is no input.csv file in the project

### ISSUE THREAD

**Issue by scorpion293** [SatCom-TELMA/MA-DRL_Routing_Simulator#1]
There is no input.csv file in the project. Can the author update it?

**Comment by Fedeloz** [comment]
Hi, thank you for the comment. I have uploaded input.csv file. This file is required for Simulation.py, which only has the deterministic Dijkstra´s based routing policies. In SimulationRL.py you can test both the deterministic routing policies and the MA-DRL based policies.
